"""New Migration

Revision ID: 013622174884
Revises: e190c42d3404
Create Date: 2023-07-21 18:07:26.598280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013622174884'
down_revision = 'e190c42d3404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
