"""New Migration

Revision ID: 1de076ca4d7d
Revises: 49a3bf35646c
Create Date: 2023-07-12 17:23:49.128076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de076ca4d7d'
down_revision = '49a3bf35646c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tabUsers', 'token')
    op.drop_column('tabUsers', 'validate_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabUsers', sa.Column('validate_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tabUsers', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
