"""New Migration

Revision ID: 27c1cfe2315d
Revises: 3dc46418cee0
Create Date: 2023-07-12 16:06:34.420100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c1cfe2315d'
down_revision = '3dc46418cee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ss')
    op.create_unique_constraint(None, 'tabUsers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tabUsers', type_='unique')
    op.create_table('ss',
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=20), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
