"""New Migration

Revision ID: 3dc46418cee0
Revises: 5a468333c19e
Create Date: 2023-07-11 17:44:17.436482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc46418cee0'
down_revision = '5a468333c19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
