"""New Migration

Revision ID: 49a3bf35646c
Revises: 27c1cfe2315d
Create Date: 2023-07-12 17:16:34.874117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a3bf35646c'
down_revision = '27c1cfe2315d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabUsers', sa.Column('token', sa.String(), nullable=True))
    op.add_column('tabUsers', sa.Column('validate_time', sa.String(), nullable=True))
    op.drop_constraint('tabUsers_email_key', 'tabUsers', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('tabUsers_email_key', 'tabUsers', ['email'])
    op.drop_column('tabUsers', 'validate_time')
    op.drop_column('tabUsers', 'token')
    # ### end Alembic commands ###
