"""New Migration

Revision ID: 57eb8f56f619
Revises: ca3b880d421b
Create Date: 2023-07-21 18:05:04.630412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57eb8f56f619'
down_revision = 'ca3b880d421b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
