"""New Migration

Revision ID: 5a468333c19e
Revises: 97ddc6770636
Create Date: 2023-07-11 17:41:11.530317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a468333c19e'
down_revision = '97ddc6770636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
