"""New Migration

Revision ID: 7668af46a3a0
Revises: 1de076ca4d7d
Create Date: 2023-07-12 18:12:57.826518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7668af46a3a0'
down_revision = '1de076ca4d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabUsers', sa.Column('token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'tabUsers', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tabUsers', type_='unique')
    op.drop_column('tabUsers', 'token')
    # ### end Alembic commands ###
