"""New Migration

Revision ID: 7cc4969b6598
Revises: 812ad75ec5af
Create Date: 2023-07-14 12:20:58.696577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cc4969b6598'
down_revision = '812ad75ec5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
