"""New Migration

Revision ID: 812ad75ec5af
Revises: 7668af46a3a0
Create Date: 2023-07-12 18:22:18.530428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '812ad75ec5af'
down_revision = '7668af46a3a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
