"""New Migration

Revision ID: ca3b880d421b
Revises: f43eb0700ca8
Create Date: 2023-07-21 17:41:57.557987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3b880d421b'
down_revision = 'f43eb0700ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
