"""New Migration

Revision ID: e190c42d3404
Revises: 57eb8f56f619
Create Date: 2023-07-21 18:06:26.391533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e190c42d3404'
down_revision = '57eb8f56f619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabUsers', sa.Column('otp', sa.String(), nullable=True))
    op.drop_column('tabUsers', 'token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tabUsers', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tabUsers', 'otp')
    # ### end Alembic commands ###
