"""New Migration

Revision ID: efd1ac5d8b1b
Revises: 013622174884
Create Date: 2023-07-24 18:37:38.607028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efd1ac5d8b1b'
down_revision = '013622174884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
