"""New Migration

Revision ID: f43eb0700ca8
Revises: 7cc4969b6598
Create Date: 2023-07-14 17:07:59.875527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43eb0700ca8'
down_revision = '7cc4969b6598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
